services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: seasonal_backend_prod
    restart: always
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: ${DATABASE_URL}
      PORT: ${PORT}
      UPLOAD_DIR: ${UPLOAD_DIR}
    volumes:
        - /mnt/nas/lineup-photos:/mnt/nas/lineup-photos
