services:
  mariadb:
    image: mariadb:latest
    container_name: seasonal_mariadb_local
    restart: always
    ports:
      - '3306:3306'
    environment:
      MARIADB_ROOT_PASSWORD: test
      MARIADB_DATABASE: test
      MARIADB_USER: test
      MARIADB_PASSWORD: test
    volumes:
      - mariadb_data:/var/lib/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

volumes:
  mariadb_data:
